import { test, expect } from '@playwright/test';

test('partial returns separate damage and maintenance restores only repaired units', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: /^Reservas/ }).click();
  await page.getByRole('button', { name: 'Novo orçamento', exact: true }).click();
  await page.getByRole('combobox', { name: 'Cliente', exact: true }).selectOption({ index: 1 });
  const start = new Date(Date.now() - 60 * 60 * 1000);
  const end = new Date(start); end.setDate(end.getDate() + 1);
  const local = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  await page.getByLabel('Retirada', { exact: true }).fill(local(start));
  await page.getByLabel('Retorno previsto').fill(local(end));
  await page.getByRole('combobox', { name: 'Material 1', exact: true }).selectOption({ label: 'Cadeira Tiffany branca' });
  await page.getByLabel('Quantidade 1').fill('10');
  await page.getByRole('button', { name: 'Salvar orçamento' }).click();
  await page.getByRole('button', { name: 'Confirmar reserva' }).click();
  await page.getByRole('button', { name: 'Marcar como separada' }).click();
  await page.getByRole('button', { name: 'Registrar entrega' }).click();
  const returns = page.getByRole('region', { name: 'Devolução e conferência' });
  await expect(returns).toBeVisible();
  await page.getByLabel('Recebido — Cadeira Tiffany branca', { exact: true }).fill('6');
  await page.getByLabel('Com avaria — Cadeira Tiffany branca').fill('2');
  await page.getByRole('button', { name: 'Registrar devolução', exact: true }).click();
  expect(await page.getByLabel('Observação da avaria — Cadeira Tiffany branca').evaluate((input: HTMLInputElement) => input.validity.valueMissing)).toBe(true);
  await expect(returns.getByText('10 un. pendentes', { exact: true })).toBeVisible();
  await page.getByLabel('Observação da avaria — Cadeira Tiffany branca').fill('Dois encostos quebrados.');
  await page.getByRole('button', { name: 'Registrar devolução', exact: true }).click();
  await expect(returns.getByText('4 un. reutilizáveis', { exact: true })).toBeVisible();
  await expect(returns.getByText('4 un. pendentes', { exact: true })).toBeVisible();
  await page.getByLabel('Recebido — Cadeira Tiffany branca', { exact: true }).fill('4');
  await page.getByRole('button', { name: 'Registrar devolução', exact: true }).click();
  await expect(page.locator('.rental-document').getByText('Devolvida', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Recebido — Cadeira Tiffany branca', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Histórico de devoluções' })).toBeVisible();
  await page.getByLabel('Quantidade liberada — Cadeira Tiffany branca').fill('1');
  await page.getByLabel('Conferência da manutenção — Cadeira Tiffany branca').fill('Encosto reparado e conferido.');
  await page.getByRole('button', { name: 'Liberar material reparado', exact: true }).click();
  await expect(page.getByText('1 un. em manutenção', { exact: true })).toBeVisible();
  await page.getByLabel('Quantidade liberada — Cadeira Tiffany branca').fill('1');
  await page.getByLabel('Conferência da manutenção — Cadeira Tiffany branca').fill('Segundo encosto reparado.');
  await page.getByRole('button', { name: 'Liberar material reparado', exact: true }).click();
  await expect(page.getByLabel('Quantidade liberada — Cadeira Tiffany branca')).toHaveCount(0);
  await page.getByRole('button', { name: 'Voltar às reservas' }).click();
  await page.getByRole('button', { name: 'Novo orçamento', exact: true }).click();
  await page.getByRole('combobox', { name: 'Cliente', exact: true }).selectOption({ index: 1 });
  await page.getByLabel('Retirada', { exact: true }).fill(local(new Date(Date.now() + 60000)));
  await page.getByLabel('Retorno previsto').fill(local(end));
  await page.getByRole('combobox', { name: 'Material 1', exact: true }).selectOption({ label: 'Cadeira Tiffany branca' });
  await page.getByLabel('Quantidade 1').fill('60');
  await page.getByRole('button', { name: 'Salvar orçamento' }).click();
  await page.getByRole('button', { name: 'Confirmar reserva' }).click();
  await expect(page.getByText('Reserva confirmada.', { exact: true })).toBeVisible();
});
