import { createServer } from 'node:http';
import { postgres, verifyRuntime } from '../../packages/database/index.ts';
import { createApp } from './app.ts';
if (!process.env.DATABASE_URL || !process.env.APP_ORIGIN) throw new Error('Defina DATABASE_URL e APP_ORIGIN.');
const production = process.env.NODE_ENV === 'production';
const origin = new URL(process.env.APP_ORIGIN).origin;
if (production && !origin.startsWith('https://')) throw new Error('APP_ORIGIN de produção deve usar HTTPS.');
const db = postgres(process.env.DATABASE_URL);
await verifyRuntime(db);
const server = createServer(createApp(db, { origin, production }));
server.requestTimeout = 30000; server.headersTimeout = 15000;
server.listen(Number(process.env.PORT ?? 3001), '127.0.0.1', () => console.log('API Tonin Loca pronta.'));
for (const signal of ['SIGINT', 'SIGTERM'] as const) process.on(signal, () => server.close(() => void db.close()));
